#!/bin/sh
module="my_module"
device="my_device"
mode="a+w"

# remove stale nodes
rm -f /dev/$device

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod -f ./$module.o $* || exit 1

major=$(cat /proc/devices | awk "\$2==\"$device\" || \$2==\"$module\" {print \$1}")

mknod /dev/$device c $major 0 || exit 2

# give appropriate group/permissions
chmod $mode  /dev/$device
